/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_MainFrame (void);
GtkWidget* create_window2 (void);
GtkWidget* create_SendFrame (void);
GtkWidget* create_fs_attachment (void);
GtkWidget* create_fs_download (void);
GtkWidget* create_FrmAccount (void);
GtkWidget* create_dg_instruction (void);
GtkWidget* create_FrmAbout (void);
