/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_MainFrame (void)
{
  GtkWidget *MainFrame;
  GtkWidget *scrolledwindow1;
  GtkWidget *layout1;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *_____________o_1;
  GtkWidget *image11;
  GtkWidget *_____________g_1;
  GtkWidget *image12;
  GtkWidget *_____________n_1;
  GtkWidget *image13;
  GtkWidget *__________a_1;
  GtkWidget *separatormenuitem1;
  GtkWidget *_______q_1;
  GtkWidget *menuitem2;
  GtkWidget *menuitem2_menu;
  GtkWidget *_______t_1;
  GtkWidget *_______c_1;
  GtkWidget *_______p_1;
  GtkWidget *_______d_1;
  GtkWidget *menuitem3;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *about1;
  GtkWidget *vseparator1;
  GtkWidget *hseparator1;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *ls_box;
  GtkWidget *label3;
  GtkWidget *ls_in;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *lb_from;
  GtkWidget *lb_to;
  GtkWidget *lb_date;
  GtkWidget *lb_subject;
  GtkWidget *btn_update;
  GtkWidget *tv_gcontent;
  GtkWidget *btn_detail;
  GtkWidget *btn_delete;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  MainFrame = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (MainFrame, 800, 600);
  gtk_window_set_title (GTK_WINDOW (MainFrame), _("MyMail"));
  gtk_window_set_resizable (GTK_WINDOW (MainFrame), FALSE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (MainFrame), TRUE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (MainFrame), scrolledwindow1);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  layout1 = gtk_layout_new (NULL, NULL);
  gtk_widget_show (layout1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), layout1);
  gtk_layout_set_size (GTK_LAYOUT (layout1), 800, 600);
  GTK_ADJUSTMENT (GTK_LAYOUT (layout1)->hadjustment)->step_increment = 10;
  GTK_ADJUSTMENT (GTK_LAYOUT (layout1)->vadjustment)->step_increment = 10;

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_layout_put (GTK_LAYOUT (layout1), menubar1, 8, 0);
  gtk_widget_set_size_request (menubar1, 784, 24);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_Set"));
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  _____________o_1 = gtk_image_menu_item_new_with_mnemonic (_("\350\256\276\347\275\256\351\200\211\351\241\271(_O)"));
  gtk_widget_show (_____________o_1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), _____________o_1);
  gtk_tooltips_set_tip (tooltips, _____________o_1, _("\350\256\276\347\275\256\345\270\220\346\210\267"), NULL);

  image11 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image11);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (_____________o_1), image11);

  _____________g_1 = gtk_image_menu_item_new_with_mnemonic (_("\346\233\264\346\224\271\345\270\220\346\210\267(_G)"));
  gtk_widget_show (_____________g_1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), _____________g_1);
  gtk_tooltips_set_tip (tooltips, _____________g_1, _("\346\233\264\346\224\271\351\202\256\344\273\266\345\270\220\346\210\267"), NULL);

  image12 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image12);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (_____________g_1), image12);

  _____________n_1 = gtk_image_menu_item_new_with_mnemonic (_("\345\217\221\351\200\201\351\202\256\344\273\266(_N)"));
  gtk_widget_show (_____________n_1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), _____________n_1);
  gtk_tooltips_set_tip (tooltips, _____________n_1, _("\345\210\233\345\273\272\346\226\260\351\202\256\344\273\266"), NULL);

  image13 = gtk_image_new_from_stock ("gtk-justify-left", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image13);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (_____________n_1), image13);

  __________a_1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (__________a_1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), __________a_1);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  _______q_1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (_______q_1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), _______q_1);

  menuitem2 = gtk_menu_item_new_with_mnemonic (_("_Edit"));
  gtk_widget_show (menuitem2);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem2);

  menuitem2_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem2), menuitem2_menu);

  _______t_1 = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
  gtk_widget_show (_______t_1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), _______t_1);

  _______c_1 = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_show (_______c_1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), _______c_1);

  _______p_1 = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_show (_______p_1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), _______p_1);

  _______d_1 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_show (_______d_1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), _______d_1);

  menuitem3 = gtk_menu_item_new_with_mnemonic (_("_View"));
  gtk_widget_show (menuitem3);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem3);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  about1 = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), about1);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_layout_put (GTK_LAYOUT (layout1), vseparator1, 160, 56);
  gtk_widget_set_size_request (vseparator1, 16, 536);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_layout_put (GTK_LAYOUT (layout1), hseparator1, 168, 240);
  gtk_widget_set_size_request (hseparator1, 616, 16);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_layout_put (GTK_LAYOUT (layout1), toolbar1, 0, 24);
  gtk_widget_set_size_request (toolbar1, 784, 32);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  ls_box = gtk_clist_new (1);
  gtk_widget_show (ls_box);
  gtk_layout_put (GTK_LAYOUT (layout1), ls_box, 0, 128);
  gtk_widget_set_size_request (ls_box, 168, 456);
  gtk_clist_set_column_width (GTK_CLIST (ls_box), 0, 80);
  gtk_clist_column_titles_hide (GTK_CLIST (ls_box));

  label3 = gtk_label_new (_("label3"));
  gtk_clist_set_column_widget (GTK_CLIST (ls_box), 0, label3);
  gtk_label_set_width_chars (GTK_LABEL (label3), 0);

  ls_in = gtk_clist_new (5);
  gtk_widget_show (ls_in);
  gtk_layout_put (GTK_LAYOUT (layout1), ls_in, 168, 56);
  gtk_widget_set_size_request (ls_in, 608, 192);
  gtk_clist_set_column_width (GTK_CLIST (ls_in), 0, 32);
  gtk_clist_set_column_width (GTK_CLIST (ls_in), 1, 143);
  gtk_clist_set_column_width (GTK_CLIST (ls_in), 2, 202);
  gtk_clist_set_column_width (GTK_CLIST (ls_in), 3, 145);
  gtk_clist_set_column_width (GTK_CLIST (ls_in), 4, 61);
  gtk_clist_column_titles_show (GTK_CLIST (ls_in));

  label7 = gtk_label_new (_("\345\272\217\345\217\267"));
  gtk_widget_show (label7);
  gtk_clist_set_column_widget (GTK_CLIST (ls_in), 0, label7);

  label8 = gtk_label_new (_("\345\217\221\344\273\266\344\272\272"));
  gtk_widget_show (label8);
  gtk_clist_set_column_widget (GTK_CLIST (ls_in), 1, label8);

  label9 = gtk_label_new (_("\346\240\207\351\242\230"));
  gtk_widget_show (label9);
  gtk_clist_set_column_widget (GTK_CLIST (ls_in), 2, label9);

  label10 = gtk_label_new (_("\346\227\245\346\234\237"));
  gtk_widget_show (label10);
  gtk_clist_set_column_widget (GTK_CLIST (ls_in), 3, label10);

  label11 = gtk_label_new (_("\351\231\204\344\273\266\357\274\237"));
  gtk_widget_show (label11);
  gtk_clist_set_column_widget (GTK_CLIST (ls_in), 4, label11);

  label12 = gtk_label_new (_("\345\217\221\344\273\266\344\272\272\357\274\232 "));
  gtk_widget_show (label12);
  gtk_layout_put (GTK_LAYOUT (layout1), label12, 176, 256);
  gtk_widget_set_size_request (label12, 47, 17);

  label13 = gtk_label_new (_("\346\224\266\344\273\266\344\272\272\357\274\232"));
  gtk_widget_show (label13);
  gtk_layout_put (GTK_LAYOUT (layout1), label13, 176, 280);
  gtk_widget_set_size_request (label13, 47, 17);

  label14 = gtk_label_new (_("\346\227\245\346\234\237\357\274\232"));
  gtk_widget_show (label14);
  gtk_layout_put (GTK_LAYOUT (layout1), label14, 184, 304);
  gtk_widget_set_size_request (label14, 47, 17);

  label15 = gtk_label_new (_("\346\240\207\351\242\230\357\274\232"));
  gtk_widget_show (label15);
  gtk_layout_put (GTK_LAYOUT (layout1), label15, 184, 328);
  gtk_widget_set_size_request (label15, 47, 17);

  lb_from = gtk_label_new ("");
  gtk_widget_show (lb_from);
  gtk_layout_put (GTK_LAYOUT (layout1), lb_from, 248, 256);
  gtk_widget_set_size_request (lb_from, 200, 24);

  lb_to = gtk_label_new ("");
  gtk_widget_show (lb_to);
  gtk_layout_put (GTK_LAYOUT (layout1), lb_to, 248, 280);
  gtk_widget_set_size_request (lb_to, 200, 24);

  lb_date = gtk_label_new ("");
  gtk_widget_show (lb_date);
  gtk_layout_put (GTK_LAYOUT (layout1), lb_date, 248, 304);
  gtk_widget_set_size_request (lb_date, 200, 24);

  lb_subject = gtk_label_new ("");
  gtk_widget_show (lb_subject);
  gtk_layout_put (GTK_LAYOUT (layout1), lb_subject, 248, 328);
  gtk_widget_set_size_request (lb_subject, 200, 24);

  btn_update = gtk_button_new_with_mnemonic (_("\346\224\266\345\217\226\351\202\256\344\273\266"));
  gtk_widget_show (btn_update);
  gtk_layout_put (GTK_LAYOUT (layout1), btn_update, 0, 56);
  gtk_widget_set_size_request (btn_update, 168, 72);

  tv_gcontent = gtk_text_view_new ();
  gtk_widget_show (tv_gcontent);
  gtk_layout_put (GTK_LAYOUT (layout1), tv_gcontent, 168, 368);
  gtk_widget_set_size_request (tv_gcontent, 608, 216);
  gtk_container_set_border_width (GTK_CONTAINER (tv_gcontent), 8);

  btn_detail = gtk_button_new_with_mnemonic (_("\347\202\271\345\207\273\346\237\245\347\234\213\351\202\256\344\273\266\350\257\246\346\203\205"));
  gtk_widget_show (btn_detail);
  gtk_layout_put (GTK_LAYOUT (layout1), btn_detail, 656, 256);
  gtk_widget_set_size_request (btn_detail, 120, 32);

  btn_delete = gtk_button_new_with_mnemonic (_("\345\210\240\351\231\244\351\202\256\344\273\266"));
  gtk_widget_show (btn_delete);
  gtk_layout_put (GTK_LAYOUT (layout1), btn_delete, 504, 256);
  gtk_widget_set_size_request (btn_delete, 112, 32);

  g_signal_connect ((gpointer) MainFrame, "destroy",
                    G_CALLBACK (on_MainFrame_destroy),
                    NULL);
  g_signal_connect ((gpointer) _____________o_1, "activate",
                    G_CALLBACK (on______________o_1_activate),
                    NULL);
  g_signal_connect ((gpointer) _____________g_1, "activate",
                    G_CALLBACK (on______________g_1_activate),
                    NULL);
  g_signal_connect ((gpointer) _____________n_1, "activate",
                    G_CALLBACK (on______________n_1_activate),
                    NULL);
  g_signal_connect ((gpointer) __________a_1, "activate",
                    G_CALLBACK (on___________a_1_activate),
                    NULL);
  g_signal_connect ((gpointer) _______q_1, "activate",
                    G_CALLBACK (on________q_1_activate),
                    NULL);
  g_signal_connect ((gpointer) _______t_1, "activate",
                    G_CALLBACK (on________t_1_activate),
                    NULL);
  g_signal_connect ((gpointer) _______c_1, "activate",
                    G_CALLBACK (on________c_1_activate),
                    NULL);
  g_signal_connect ((gpointer) _______p_1, "activate",
                    G_CALLBACK (on________p_1_activate),
                    NULL);
  g_signal_connect ((gpointer) _______d_1, "activate",
                    G_CALLBACK (on________d_1_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) ls_box, "select_row",
                    G_CALLBACK (on_ls_box_select_row),
                    NULL);
  g_signal_connect ((gpointer) ls_in, "select_row",
                    G_CALLBACK (on_ls_in_select_row),
                    NULL);
  g_signal_connect ((gpointer) btn_update, "clicked",
                    G_CALLBACK (on_btn_update_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_detail, "clicked",
                    G_CALLBACK (on_btn_detail_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_delete, "clicked",
                    G_CALLBACK (on_btn_delete_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MainFrame, MainFrame, "MainFrame");
  GLADE_HOOKUP_OBJECT (MainFrame, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (MainFrame, layout1, "layout1");
  GLADE_HOOKUP_OBJECT (MainFrame, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (MainFrame, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (MainFrame, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (MainFrame, _____________o_1, "_____________o_1");
  GLADE_HOOKUP_OBJECT (MainFrame, image11, "image11");
  GLADE_HOOKUP_OBJECT (MainFrame, _____________g_1, "_____________g_1");
  GLADE_HOOKUP_OBJECT (MainFrame, image12, "image12");
  GLADE_HOOKUP_OBJECT (MainFrame, _____________n_1, "_____________n_1");
  GLADE_HOOKUP_OBJECT (MainFrame, image13, "image13");
  GLADE_HOOKUP_OBJECT (MainFrame, __________a_1, "__________a_1");
  GLADE_HOOKUP_OBJECT (MainFrame, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (MainFrame, _______q_1, "_______q_1");
  GLADE_HOOKUP_OBJECT (MainFrame, menuitem2, "menuitem2");
  GLADE_HOOKUP_OBJECT (MainFrame, menuitem2_menu, "menuitem2_menu");
  GLADE_HOOKUP_OBJECT (MainFrame, _______t_1, "_______t_1");
  GLADE_HOOKUP_OBJECT (MainFrame, _______c_1, "_______c_1");
  GLADE_HOOKUP_OBJECT (MainFrame, _______p_1, "_______p_1");
  GLADE_HOOKUP_OBJECT (MainFrame, _______d_1, "_______d_1");
  GLADE_HOOKUP_OBJECT (MainFrame, menuitem3, "menuitem3");
  GLADE_HOOKUP_OBJECT (MainFrame, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (MainFrame, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (MainFrame, about1, "about1");
  GLADE_HOOKUP_OBJECT (MainFrame, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (MainFrame, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (MainFrame, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (MainFrame, ls_box, "ls_box");
  GLADE_HOOKUP_OBJECT (MainFrame, label3, "label3");
  GLADE_HOOKUP_OBJECT (MainFrame, ls_in, "ls_in");
  GLADE_HOOKUP_OBJECT (MainFrame, label7, "label7");
  GLADE_HOOKUP_OBJECT (MainFrame, label8, "label8");
  GLADE_HOOKUP_OBJECT (MainFrame, label9, "label9");
  GLADE_HOOKUP_OBJECT (MainFrame, label10, "label10");
  GLADE_HOOKUP_OBJECT (MainFrame, label11, "label11");
  GLADE_HOOKUP_OBJECT (MainFrame, label12, "label12");
  GLADE_HOOKUP_OBJECT (MainFrame, label13, "label13");
  GLADE_HOOKUP_OBJECT (MainFrame, label14, "label14");
  GLADE_HOOKUP_OBJECT (MainFrame, label15, "label15");
  GLADE_HOOKUP_OBJECT (MainFrame, lb_from, "lb_from");
  GLADE_HOOKUP_OBJECT (MainFrame, lb_to, "lb_to");
  GLADE_HOOKUP_OBJECT (MainFrame, lb_date, "lb_date");
  GLADE_HOOKUP_OBJECT (MainFrame, lb_subject, "lb_subject");
  GLADE_HOOKUP_OBJECT (MainFrame, btn_update, "btn_update");
  GLADE_HOOKUP_OBJECT (MainFrame, tv_gcontent, "tv_gcontent");
  GLADE_HOOKUP_OBJECT (MainFrame, btn_detail, "btn_detail");
  GLADE_HOOKUP_OBJECT (MainFrame, btn_delete, "btn_delete");
  GLADE_HOOKUP_OBJECT_NO_REF (MainFrame, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (MainFrame), accel_group);

  return MainFrame;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *scrolledwindow2;
  GtkWidget *layout2;
  GtkWidget *label20;
  GtkWidget *txb_address;
  GtkWidget *label21;
  GtkWidget *txb_name;
  GtkWidget *label22;
  GtkWidget *txb_smtp;
  GtkWidget *label23;
  GtkWidget *txb_pop;
  GtkWidget *btn_ok;
  GtkWidget *btn_cancle;
  GtkWidget *label28;
  GtkWidget *txb_password;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window2, 350, 320);
  gtk_window_set_title (GTK_WINDOW (window2), _("\351\202\256\347\256\261\350\256\276\347\275\256"));
  gtk_window_set_modal (GTK_WINDOW (window2), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (window2), FALSE);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (window2), scrolledwindow2);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  layout2 = gtk_layout_new (NULL, NULL);
  gtk_widget_show (layout2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), layout2);
  gtk_layout_set_size (GTK_LAYOUT (layout2), 300, 200);
  GTK_ADJUSTMENT (GTK_LAYOUT (layout2)->hadjustment)->step_increment = 10;
  GTK_ADJUSTMENT (GTK_LAYOUT (layout2)->vadjustment)->step_increment = 10;

  label20 = gtk_label_new (_("\345\234\260\345\235\200\357\274\232"));
  gtk_widget_show (label20);
  gtk_layout_put (GTK_LAYOUT (layout2), label20, 48, 40);
  gtk_widget_set_size_request (label20, 40, 16);

  txb_address = gtk_entry_new ();
  gtk_widget_show (txb_address);
  gtk_layout_put (GTK_LAYOUT (layout2), txb_address, 112, 32);
  gtk_widget_set_size_request (txb_address, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (txb_address), 8226);

  label21 = gtk_label_new (_("\345\247\223\345\220\215\357\274\232"));
  gtk_widget_show (label21);
  gtk_layout_put (GTK_LAYOUT (layout2), label21, 48, 80);
  gtk_widget_set_size_request (label21, 40, 16);

  txb_name = gtk_entry_new ();
  gtk_widget_show (txb_name);
  gtk_layout_put (GTK_LAYOUT (layout2), txb_name, 112, 72);
  gtk_widget_set_size_request (txb_name, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (txb_name), 8226);

  label22 = gtk_label_new (_("SMTP\357\274\232"));
  gtk_widget_show (label22);
  gtk_layout_put (GTK_LAYOUT (layout2), label22, 48, 160);
  gtk_widget_set_size_request (label22, 48, 16);

  txb_smtp = gtk_entry_new ();
  gtk_widget_show (txb_smtp);
  gtk_layout_put (GTK_LAYOUT (layout2), txb_smtp, 112, 152);
  gtk_widget_set_size_request (txb_smtp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (txb_smtp), 8226);

  label23 = gtk_label_new (_("POP\357\274\232"));
  gtk_widget_show (label23);
  gtk_layout_put (GTK_LAYOUT (layout2), label23, 48, 200);
  gtk_widget_set_size_request (label23, 48, 16);

  txb_pop = gtk_entry_new ();
  gtk_widget_show (txb_pop);
  gtk_layout_put (GTK_LAYOUT (layout2), txb_pop, 112, 192);
  gtk_widget_set_size_request (txb_pop, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (txb_pop), 8226);

  btn_ok = gtk_button_new_with_mnemonic (_("\347\241\256\345\256\232"));
  gtk_widget_show (btn_ok);
  gtk_layout_put (GTK_LAYOUT (layout2), btn_ok, 72, 248);
  gtk_widget_set_size_request (btn_ok, 66, 29);

  btn_cancle = gtk_button_new_with_mnemonic (_("\345\217\226\346\266\210"));
  gtk_widget_show (btn_cancle);
  gtk_layout_put (GTK_LAYOUT (layout2), btn_cancle, 200, 248);
  gtk_widget_set_size_request (btn_cancle, 66, 29);

  label28 = gtk_label_new (_("\345\257\206\347\240\201\357\274\232"));
  gtk_widget_show (label28);
  gtk_layout_put (GTK_LAYOUT (layout2), label28, 40, 120);
  gtk_widget_set_size_request (label28, 55, 16);

  txb_password = gtk_entry_new ();
  gtk_widget_show (txb_password);
  gtk_layout_put (GTK_LAYOUT (layout2), txb_password, 112, 112);
  gtk_widget_set_size_request (txb_password, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (txb_password), FALSE);

  g_signal_connect ((gpointer) btn_ok, "clicked",
                    G_CALLBACK (on_btn_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_cancle, "clicked",
                    G_CALLBACK (on_btn_cancle_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (window2, layout2, "layout2");
  GLADE_HOOKUP_OBJECT (window2, label20, "label20");
  GLADE_HOOKUP_OBJECT (window2, txb_address, "txb_address");
  GLADE_HOOKUP_OBJECT (window2, label21, "label21");
  GLADE_HOOKUP_OBJECT (window2, txb_name, "txb_name");
  GLADE_HOOKUP_OBJECT (window2, label22, "label22");
  GLADE_HOOKUP_OBJECT (window2, txb_smtp, "txb_smtp");
  GLADE_HOOKUP_OBJECT (window2, label23, "label23");
  GLADE_HOOKUP_OBJECT (window2, txb_pop, "txb_pop");
  GLADE_HOOKUP_OBJECT (window2, btn_ok, "btn_ok");
  GLADE_HOOKUP_OBJECT (window2, btn_cancle, "btn_cancle");
  GLADE_HOOKUP_OBJECT (window2, label28, "label28");
  GLADE_HOOKUP_OBJECT (window2, txb_password, "txb_password");

  return window2;
}

GtkWidget*
create_SendFrame (void)
{
  GtkWidget *SendFrame;
  GtkWidget *scrolledwindow3;
  GtkWidget *layout3;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *txb_attach;
  GtkWidget *txb_subject;
  GtkWidget *txb_to;
  GtkWidget *btn_send;
  GtkWidget *tv_content;
  GtkWidget *btn_attachment;
  GtkWidget *btn_download;

  SendFrame = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (SendFrame, 600, 500);
  gtk_window_set_title (GTK_WINDOW (SendFrame), _("\345\217\221\351\200\201/\346\237\245\347\234\213\351\202\256\344\273\266"));
  gtk_window_set_resizable (GTK_WINDOW (SendFrame), FALSE);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (SendFrame), scrolledwindow3);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_IN);

  layout3 = gtk_layout_new (NULL, NULL);
  gtk_widget_show (layout3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), layout3);
  gtk_layout_set_size (GTK_LAYOUT (layout3), 580, 480);
  GTK_ADJUSTMENT (GTK_LAYOUT (layout3)->hadjustment)->step_increment = 10;
  GTK_ADJUSTMENT (GTK_LAYOUT (layout3)->vadjustment)->step_increment = 10;

  label24 = gtk_label_new (_("\346\224\266\344\273\266\344\272\272\357\274\232"));
  gtk_widget_show (label24);
  gtk_layout_put (GTK_LAYOUT (layout3), label24, 56, 80);
  gtk_widget_set_size_request (label24, 47, 17);

  label25 = gtk_label_new (_("\346\240\207\351\242\230\357\274\232"));
  gtk_widget_show (label25);
  gtk_layout_put (GTK_LAYOUT (layout3), label25, 48, 112);
  gtk_widget_set_size_request (label25, 55, 16);

  label26 = gtk_label_new (_("\351\231\204\344\273\266\357\274\232"));
  gtk_widget_show (label26);
  gtk_layout_put (GTK_LAYOUT (layout3), label26, 48, 144);
  gtk_widget_set_size_request (label26, 55, 16);

  label27 = gtk_label_new (_("\346\255\243\346\226\207\357\274\232"));
  gtk_widget_show (label27);
  gtk_layout_put (GTK_LAYOUT (layout3), label27, 48, 176);
  gtk_widget_set_size_request (label27, 55, 16);

  txb_attach = gtk_entry_new ();
  gtk_widget_show (txb_attach);
  gtk_layout_put (GTK_LAYOUT (layout3), txb_attach, 112, 144);
  gtk_widget_set_size_request (txb_attach, 384, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (txb_attach), 8226);

  txb_subject = gtk_entry_new ();
  gtk_widget_show (txb_subject);
  gtk_layout_put (GTK_LAYOUT (layout3), txb_subject, 112, 112);
  gtk_widget_set_size_request (txb_subject, 384, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (txb_subject), 8226);

  txb_to = gtk_entry_new ();
  gtk_widget_show (txb_to);
  gtk_layout_put (GTK_LAYOUT (layout3), txb_to, 112, 80);
  gtk_widget_set_size_request (txb_to, 384, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (txb_to), 8226);

  btn_send = gtk_button_new_with_mnemonic (_("\345\217\221\351\200\201"));
  gtk_widget_show (btn_send);
  gtk_layout_put (GTK_LAYOUT (layout3), btn_send, 56, 24);
  gtk_widget_set_size_request (btn_send, 66, 29);

  tv_content = gtk_text_view_new ();
  gtk_widget_show (tv_content);
  gtk_layout_put (GTK_LAYOUT (layout3), tv_content, 56, 208);
  gtk_widget_set_size_request (tv_content, 440, 264);
  gtk_container_set_border_width (GTK_CONTAINER (tv_content), 5);

  btn_attachment = gtk_button_new_with_mnemonic (_("\346\267\273\345\212\240\351\231\204\344\273\266"));
  gtk_widget_show (btn_attachment);
  gtk_layout_put (GTK_LAYOUT (layout3), btn_attachment, 424, 176);
  gtk_widget_set_size_request (btn_attachment, 64, 29);

  btn_download = gtk_button_new_with_mnemonic (_("\344\270\213\350\275\275\351\231\204\344\273\266"));
  gtk_widget_show (btn_download);
  gtk_layout_put (GTK_LAYOUT (layout3), btn_download, 344, 176);
  gtk_widget_set_size_request (btn_download, 64, 29);

  g_signal_connect ((gpointer) btn_send, "clicked",
                    G_CALLBACK (on_btn_send_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_attachment, "clicked",
                    G_CALLBACK (on_btn_attachment_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_download, "clicked",
                    G_CALLBACK (on_btn_download_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (SendFrame, SendFrame, "SendFrame");
  GLADE_HOOKUP_OBJECT (SendFrame, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (SendFrame, layout3, "layout3");
  GLADE_HOOKUP_OBJECT (SendFrame, label24, "label24");
  GLADE_HOOKUP_OBJECT (SendFrame, label25, "label25");
  GLADE_HOOKUP_OBJECT (SendFrame, label26, "label26");
  GLADE_HOOKUP_OBJECT (SendFrame, label27, "label27");
  GLADE_HOOKUP_OBJECT (SendFrame, txb_attach, "txb_attach");
  GLADE_HOOKUP_OBJECT (SendFrame, txb_subject, "txb_subject");
  GLADE_HOOKUP_OBJECT (SendFrame, txb_to, "txb_to");
  GLADE_HOOKUP_OBJECT (SendFrame, btn_send, "btn_send");
  GLADE_HOOKUP_OBJECT (SendFrame, tv_content, "tv_content");
  GLADE_HOOKUP_OBJECT (SendFrame, btn_attachment, "btn_attachment");
  GLADE_HOOKUP_OBJECT (SendFrame, btn_download, "btn_download");

  return SendFrame;
}

GtkWidget*
create_fs_attachment (void)
{
  GtkWidget *fs_attachment;
  GtkWidget *fs_attachment_btn_ok;
  GtkWidget *fs_attachment_btn_cancel;

  fs_attachment = gtk_file_selection_new (_("\351\200\211\346\213\251\351\231\204\344\273\266"));
  gtk_container_set_border_width (GTK_CONTAINER (fs_attachment), 10);
  gtk_window_set_type_hint (GTK_WINDOW (fs_attachment), GDK_WINDOW_TYPE_HINT_DIALOG);

  fs_attachment_btn_ok = GTK_FILE_SELECTION (fs_attachment)->ok_button;
  gtk_widget_show (fs_attachment_btn_ok);
  GTK_WIDGET_SET_FLAGS (fs_attachment_btn_ok, GTK_CAN_DEFAULT);

  fs_attachment_btn_cancel = GTK_FILE_SELECTION (fs_attachment)->cancel_button;
  gtk_widget_show (fs_attachment_btn_cancel);
  GTK_WIDGET_SET_FLAGS (fs_attachment_btn_cancel, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) fs_attachment_btn_ok, "clicked",
                    G_CALLBACK (on_fs_attachment_btn_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fs_attachment, fs_attachment, "fs_attachment");
  GLADE_HOOKUP_OBJECT_NO_REF (fs_attachment, fs_attachment_btn_ok, "fs_attachment_btn_ok");
  GLADE_HOOKUP_OBJECT_NO_REF (fs_attachment, fs_attachment_btn_cancel, "fs_attachment_btn_cancel");

  return fs_attachment;
}

GtkWidget*
create_fs_download (void)
{
  GtkWidget *fs_download;
  GtkWidget *fs_download_btn_ok;
  GtkWidget *fs_download_btn_cancel;

  fs_download = gtk_file_selection_new (_("\344\270\213\350\275\275\351\231\204\344\273\266"));
  gtk_container_set_border_width (GTK_CONTAINER (fs_download), 10);
  gtk_window_set_type_hint (GTK_WINDOW (fs_download), GDK_WINDOW_TYPE_HINT_DIALOG);

  fs_download_btn_ok = GTK_FILE_SELECTION (fs_download)->ok_button;
  gtk_widget_show (fs_download_btn_ok);
  GTK_WIDGET_SET_FLAGS (fs_download_btn_ok, GTK_CAN_DEFAULT);

  fs_download_btn_cancel = GTK_FILE_SELECTION (fs_download)->cancel_button;
  gtk_widget_show (fs_download_btn_cancel);
  GTK_WIDGET_SET_FLAGS (fs_download_btn_cancel, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) fs_download_btn_ok, "clicked",
                    G_CALLBACK (on_fs_download_btn_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fs_download, fs_download, "fs_download");
  GLADE_HOOKUP_OBJECT_NO_REF (fs_download, fs_download_btn_ok, "fs_download_btn_ok");
  GLADE_HOOKUP_OBJECT_NO_REF (fs_download, fs_download_btn_cancel, "fs_download_btn_cancel");

  return fs_download;
}

GtkWidget*
create_FrmAccount (void)
{
  GtkWidget *FrmAccount;
  GtkWidget *scrolledwindow4;
  GtkWidget *layout4;
  GtkWidget *lst_account;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *lb_account_name;
  GtkWidget *lb_account_address;
  GtkWidget *lb_account_password;
  GtkWidget *lb_account_smtp;
  GtkWidget *lb_account_pop;
  GtkWidget *btn_account_ok;

  FrmAccount = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (FrmAccount, 560, 400);
  gtk_window_set_title (GTK_WINDOW (FrmAccount), _("\346\233\264\346\224\271\345\270\220\346\210\267"));
  gtk_window_set_resizable (GTK_WINDOW (FrmAccount), FALSE);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_container_add (GTK_CONTAINER (FrmAccount), scrolledwindow4);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_SHADOW_IN);

  layout4 = gtk_layout_new (NULL, NULL);
  gtk_widget_show (layout4);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), layout4);
  gtk_layout_set_size (GTK_LAYOUT (layout4), 400, 400);
  GTK_ADJUSTMENT (GTK_LAYOUT (layout4)->hadjustment)->step_increment = 10;
  GTK_ADJUSTMENT (GTK_LAYOUT (layout4)->vadjustment)->step_increment = 10;

  lst_account = gtk_clist_new (1);
  gtk_widget_show (lst_account);
  gtk_layout_put (GTK_LAYOUT (layout4), lst_account, 16, 40);
  gtk_widget_set_size_request (lst_account, 168, 272);
  gtk_clist_set_column_width (GTK_CLIST (lst_account), 0, 80);
  gtk_clist_column_titles_show (GTK_CLIST (lst_account));

  label29 = gtk_label_new (_("\345\270\220\346\210\267\345\220\215\347\247\260"));
  gtk_widget_show (label29);
  gtk_clist_set_column_widget (GTK_CLIST (lst_account), 0, label29);

  label30 = gtk_label_new (_("\347\224\250\346\210\267\345\270\220\346\210\267\357\274\232"));
  gtk_widget_show (label30);
  gtk_layout_put (GTK_LAYOUT (layout4), label30, 208, 72);
  gtk_widget_set_size_request (label30, 64, 16);

  label31 = gtk_label_new (_("\345\234\260\345\235\200\357\274\232"));
  gtk_widget_show (label31);
  gtk_layout_put (GTK_LAYOUT (layout4), label31, 200, 112);
  gtk_widget_set_size_request (label31, 64, 16);

  label32 = gtk_label_new (_("\345\257\206\347\240\201\357\274\232"));
  gtk_widget_show (label32);
  gtk_layout_put (GTK_LAYOUT (layout4), label32, 200, 152);
  gtk_widget_set_size_request (label32, 64, 16);

  label33 = gtk_label_new (_("SMTP\357\274\232"));
  gtk_widget_show (label33);
  gtk_layout_put (GTK_LAYOUT (layout4), label33, 200, 192);
  gtk_widget_set_size_request (label33, 72, 16);

  label34 = gtk_label_new (_("POP\357\274\232"));
  gtk_widget_show (label34);
  gtk_layout_put (GTK_LAYOUT (layout4), label34, 208, 232);
  gtk_widget_set_size_request (label34, 48, 16);

  lb_account_name = gtk_label_new (_("NULL"));
  gtk_widget_show (lb_account_name);
  gtk_layout_put (GTK_LAYOUT (layout4), lb_account_name, 304, 72);
  gtk_widget_set_size_request (lb_account_name, 200, 16);

  lb_account_address = gtk_label_new (_("NULL"));
  gtk_widget_show (lb_account_address);
  gtk_layout_put (GTK_LAYOUT (layout4), lb_account_address, 304, 112);
  gtk_widget_set_size_request (lb_account_address, 200, 16);

  lb_account_password = gtk_label_new (_("NULL"));
  gtk_widget_show (lb_account_password);
  gtk_layout_put (GTK_LAYOUT (layout4), lb_account_password, 304, 152);
  gtk_widget_set_size_request (lb_account_password, 200, 16);

  lb_account_smtp = gtk_label_new (_("NULL"));
  gtk_widget_show (lb_account_smtp);
  gtk_layout_put (GTK_LAYOUT (layout4), lb_account_smtp, 304, 192);
  gtk_widget_set_size_request (lb_account_smtp, 200, 16);

  lb_account_pop = gtk_label_new (_("NULL"));
  gtk_widget_show (lb_account_pop);
  gtk_layout_put (GTK_LAYOUT (layout4), lb_account_pop, 304, 232);
  gtk_widget_set_size_request (lb_account_pop, 200, 16);

  btn_account_ok = gtk_button_new_with_mnemonic (_("\347\241\256\345\256\232"));
  gtk_widget_show (btn_account_ok);
  gtk_layout_put (GTK_LAYOUT (layout4), btn_account_ok, 264, 280);
  gtk_widget_set_size_request (btn_account_ok, 66, 29);

  g_signal_connect ((gpointer) lst_account, "select_row",
                    G_CALLBACK (on_lst_account_select_row),
                    NULL);
  g_signal_connect ((gpointer) btn_account_ok, "clicked",
                    G_CALLBACK (on_btn_account_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (FrmAccount, FrmAccount, "FrmAccount");
  GLADE_HOOKUP_OBJECT (FrmAccount, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (FrmAccount, layout4, "layout4");
  GLADE_HOOKUP_OBJECT (FrmAccount, lst_account, "lst_account");
  GLADE_HOOKUP_OBJECT (FrmAccount, label29, "label29");
  GLADE_HOOKUP_OBJECT (FrmAccount, label30, "label30");
  GLADE_HOOKUP_OBJECT (FrmAccount, label31, "label31");
  GLADE_HOOKUP_OBJECT (FrmAccount, label32, "label32");
  GLADE_HOOKUP_OBJECT (FrmAccount, label33, "label33");
  GLADE_HOOKUP_OBJECT (FrmAccount, label34, "label34");
  GLADE_HOOKUP_OBJECT (FrmAccount, lb_account_name, "lb_account_name");
  GLADE_HOOKUP_OBJECT (FrmAccount, lb_account_address, "lb_account_address");
  GLADE_HOOKUP_OBJECT (FrmAccount, lb_account_password, "lb_account_password");
  GLADE_HOOKUP_OBJECT (FrmAccount, lb_account_smtp, "lb_account_smtp");
  GLADE_HOOKUP_OBJECT (FrmAccount, lb_account_pop, "lb_account_pop");
  GLADE_HOOKUP_OBJECT (FrmAccount, btn_account_ok, "btn_account_ok");

  return FrmAccount;
}

GtkWidget*
create_dg_instruction (void)
{
  GtkWidget *dg_instruction;
  GtkWidget *dialog_vbox1;
  GtkWidget *scrolledwindow5;
  GtkWidget *layout5;
  GtkWidget *label40;
  GtkWidget *lb_message;
  GtkWidget *dialog_action_area1;
  GtkWidget *btn_dlg_ok;

  dg_instruction = gtk_dialog_new ();
  gtk_widget_set_size_request (dg_instruction, 300, 150);
  gtk_window_set_title (GTK_WINDOW (dg_instruction), _("\344\277\241\346\201\257\346\217\220\347\244\272"));
  gtk_window_set_resizable (GTK_WINDOW (dg_instruction), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (dg_instruction), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (dg_instruction)->vbox;
  gtk_widget_show (dialog_vbox1);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), scrolledwindow5, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_NEVER, GTK_POLICY_NEVER);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_SHADOW_IN);

  layout5 = gtk_layout_new (NULL, NULL);
  gtk_widget_show (layout5);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), layout5);
  gtk_widget_set_size_request (layout5, 400, 200);
  gtk_layout_set_size (GTK_LAYOUT (layout5), 206, 78);
  GTK_ADJUSTMENT (GTK_LAYOUT (layout5)->hadjustment)->step_increment = 10;
  GTK_ADJUSTMENT (GTK_LAYOUT (layout5)->vadjustment)->step_increment = 10;

  label40 = gtk_label_new (_("\344\277\241\346\201\257\357\274\232"));
  gtk_widget_show (label40);
  gtk_layout_put (GTK_LAYOUT (layout5), label40, 24, 16);
  gtk_widget_set_size_request (label40, 47, 17);

  lb_message = gtk_label_new ("");
  gtk_widget_show (lb_message);
  gtk_layout_put (GTK_LAYOUT (layout5), lb_message, 24, 48);
  gtk_widget_set_size_request (lb_message, 264, 24);

  dialog_action_area1 = GTK_DIALOG (dg_instruction)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  btn_dlg_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (btn_dlg_ok);
  gtk_dialog_add_action_widget (GTK_DIALOG (dg_instruction), btn_dlg_ok, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (btn_dlg_ok, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) btn_dlg_ok, "clicked",
                    G_CALLBACK (on_btn_dlg_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dg_instruction, dg_instruction, "dg_instruction");
  GLADE_HOOKUP_OBJECT_NO_REF (dg_instruction, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dg_instruction, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (dg_instruction, layout5, "layout5");
  GLADE_HOOKUP_OBJECT (dg_instruction, label40, "label40");
  GLADE_HOOKUP_OBJECT (dg_instruction, lb_message, "lb_message");
  GLADE_HOOKUP_OBJECT_NO_REF (dg_instruction, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dg_instruction, btn_dlg_ok, "btn_dlg_ok");

  return dg_instruction;
}

GtkWidget*
create_FrmAbout (void)
{
  GtkWidget *FrmAbout;
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator-credits");

  FrmAbout = gtk_about_dialog_new ();
  gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (FrmAbout), VERSION);
  gtk_about_dialog_set_name (GTK_ABOUT_DIALOG (FrmAbout), _("Achillean Mail"));
  gtk_about_dialog_set_comments (GTK_ABOUT_DIALOG (FrmAbout), _("\344\275\234\350\200\205\357\274\23210717169 \346\235\216\345\215\232\n                 10717362 \347\277\237\346\201\251\345\215\227\n            10717365 \345\274\240\345\215\232\n                10717382 \345\274\240\346\257\205\345\244\253"));
  gtk_about_dialog_set_translator_credits (GTK_ABOUT_DIALOG (FrmAbout), translators);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (FrmAbout, FrmAbout, "FrmAbout");

  return FrmAbout;
}

