/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *MainFrame;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  MainFrame = create_MainFrame ();
  gtk_widget_show (MainFrame);
  GtkWidget* mylist = lookup_widget(MainFrame,"ls_box");
  char* box[5][1];
  int i;
  box[0][0] = "收件箱";
  box[1][0] = "已发邮件";
  box[2][0] = "垃圾箱";
  box[3][0] = "发件箱";
  box[4][0] = "草稿箱";


  for(i = 0; i < 5; i++)
  {
  	gtk_clist_append((GtkCList*)mylist,box[i]);
  }
  addfunc();
 // strcpy(storename,"10717365");
 // strcpy(storeaddress,"10717365@pub.ss.pku.edu.cn");
 // strcpy(storepassword,"6188699");
  gtk_main ();
  return 0;
}

